Feat/nav bar
estartandodevs-course/kognito-frontend pull request #23
Opened 2024-11-16 03:51 UTC by lyumiks

# Título

Criação da navbar de estudante e professor (mobile)

## Descrição da Merge Request

Adiciona o componente **Navbar**, tanto de estudante quanto de professor, com lógica para alteração dinâmica entre as duas navbars com base no tipo de usuário. OBS.: O componente ainda não está responsivo.

## Issue ou Card Relacionado

- https://trello.com/c/ohtCdJF7/12-component-navbar-mobile

## Passos para Testar

1. Verifique a renderização da Navbar tanto para estudante quanto para professor.

2024-11-16 14:47 UTC, rkalbuqp commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.scss
> +  grid-template-columns: 1fr 1fr 1fr;
Caso queiras, fica de sugestão mesmo, podes usar o mixin da grid que estamos usando. Só pra padronizaar o uso mesmo.

@mixin applyGridColumns($columns, $minSize, $maxSize, $gap: 0, $alignItems: stretch, $justifyItems: stretch) {
  display: grid;
  grid-template-columns: repeat($columns, minmax($minSize, $maxSize));
  gap: $gap;
  align-items: $alignItems;
  justify-items: $justifyItems;
}

Para passar, você usa o applyGridColumns e, entre os parenteses, você substitui essas variáveis que têm $ pelo valor que deseja, puro mesmo, como seria em css normal.

2024-11-16 14:48 UTC, rkalbuqp commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.scss
> +  stroke: var(--gray-1);
Você pode aninhar essas svg em uma só. 

svg {
  stroke: var(--gray-1);
  
  &.settings {
    fill: var(--light);
  }
}


tipo assim. Usando o & para sinalizar ao motor de leitura de código que também é parte ali.

2024-11-16 14:51 UTC, rkalbuqp commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.scss
> +.icon-unselected {
Tu consegues aninhar o selected e o unselected em bloco, caso queiras. 

Fica melhor de ler e manipular depois.

.icon {
  width: 2rem;
  height: 2rem;

  &-selected {
    fill: var(--normal);
    color: var(--normal);
  }

  &-unselected {
    fill: var(--light);
    color: var(--gray-1);
  }
}


tipo nessa pegada aqui

2024-11-16 14:55 UTC, rkalbuqp commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.html
Só sugestão aqui também: 
Como utilizamos uma mesma lógica para os ícones, podemos adicionar no TS algo para isso.

Fiz um esboço aqui de como poderia ser aplicado:

// Exemplo de um componente simplificado para um item de navegação
@Component({
  selector: 'app-nav-item',
  template: `
    <a [routerLink]="link" [class.selected]="path === link">
      <span
        class="iconify"
        [ngClass]="{ 'icon-selected': path === link, 'icon-unselected': path !== link }"
        [attr.data-icon]="path === link ? selectedIcon : unselectedIcon"
      ></span>
      <p [ngClass]="{ 'label-selected': path === link, 'label-unselected': path !== link }">{{ label }}</p>
    </a>
  `,
})
export class NavItemComponent {
  @Input() link!: string;
  @Input() selectedIcon!: string;
  @Input() unselectedIcon!: string;
  @Input() label!: string;
  @Input() path!: string; // Passe o valor de path do componente pai
}


esse sendo o TS.

Com isso, o HTML poderia ficar nessa pegada aqui:
<a routerLink="/tarefas" [class.selected]="path === '/tarefas'">
  <span
    class="iconify"
    [ngClass]="{ 'icon-selected': path === '/tarefas', 'icon-unselected': path !== '/tarefas' }"
    data-icon="majesticons:book-open"
    [attr.data-icon]="path === '/tarefas' ? 'majesticons:book-open' : 'majesticons:book-open-line'"
  ></span>
  <p [ngClass]="{ 'label-selected': path === '/tarefas', 'label-unselected': path !== '/tarefas' }">
    Tarefas
  </p>
</a>


E daí conseguiria escrever bem menos, porque consegues reaproveitar em ambas Nav-bar.


MAAAAS, só uma sugestão de melhoria mesmo. Da maneira que está é super aplicável, tá?

2024-11-16 14:56 UTC, rkalbuqp commented on src/app/shared/components/navbar/navbar-teacher/navbar-teacher.component.scss
As sugestões da nav-bar student se aplicam aqui também. A questão do template grid de mixin, o aninhamento (Nesting) de classes em blocos e tal.

2024-11-16 15:01 UTC, rkalbuqp requested changes
Deixei algumas sugestões ao longo do código.

São apenas sugestões de melhoria.

2024-11-17 01:32 UTC, lyumiks commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.scss
> +.icon-unselected {
Realmente fica melhor de ler! Tentei fazer dessa forma, mas não rolou :( 

Porque teria que criar uma classe "icon", mas ficariam duas classes: uma "icon-selected" e outra só "icon", talvez não fique muito legal assim. E para evitar essa repetição, chamaria uma classe somente de "selected", por exemplo, aí não daria para aninhar :(((

2024-11-17 01:33 UTC, rkalbuqp commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.scss
> +.icon-unselected {
Tranquilo então, nega!

2024-11-17 02:03 UTC, rkalbuqp commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.html
> +        <span class="iconify icon-selected" data-icon="majesticons:book-open"></span>
Shoooooow

Bem melhor de conseguir enxergar e entender o que está acontecendo!

2024-11-17 02:53 UTC, lyumiks commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.html
Feito!

2024-11-17 02:54 UTC, lyumiks commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.scss
> +  grid-template-columns: 1fr 1fr 1fr;
Shoow, usei o mixin no último commit

2024-11-17 02:55 UTC, lyumiks commented on src/app/shared/components/navbar/navbar-student/navbar-student.component.html
> +        <span class="iconify icon-selected" data-icon="majesticons:book-open"></span>
Acabei utilizando a forma que sugeriu, ficaram bem menos linhas de código. Acredito que ficou melhor de interpretá-lo

2024-11-17 10:58 UTC, rkalbuqp approved these changes
MR aprovada

2024-11-17 18:12 UTC, merged